/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * RAG Document Chat API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Document,
  DocumentsArray,
  ErrorResponse,
  MessageResponse,
  UploadDocumentRequest
} from '.././model';

import { axios } from '.././axios';
import type { ErrorType , BodyType } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Upload a document
 */
export const postDocumentCreate = (
    uploadDocumentRequest: BodyType<UploadDocumentRequest>,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {
      
      const formData = new FormData();
      formData.append(
        "file",
        uploadDocumentRequest.file
      );

      return axios<MessageResponse>(
      {url: `/document/create`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      options);
    }
  


export const getPostDocumentCreateMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postDocumentCreate>>, TError,{data: BodyType<UploadDocumentRequest>}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof postDocumentCreate>>, TError,{data: BodyType<UploadDocumentRequest>}, TContext> => {

const mutationKey = ['postDocumentCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postDocumentCreate>>, {data: BodyType<UploadDocumentRequest>}> = (props) => {
          const {data} = props ?? {};

          return  postDocumentCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostDocumentCreateMutationResult = NonNullable<Awaited<ReturnType<typeof postDocumentCreate>>>
    export type PostDocumentCreateMutationBody = BodyType<UploadDocumentRequest>
    export type PostDocumentCreateMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Upload a document
 */
export const usePostDocumentCreate = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postDocumentCreate>>, TError,{data: BodyType<UploadDocumentRequest>}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postDocumentCreate>>,
        TError,
        {data: BodyType<UploadDocumentRequest>},
        TContext
      > => {

      const mutationOptions = getPostDocumentCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete a document
 */
export const deleteDocumentDeleteId = (
    id: string,
 options?: SecondParameter<typeof axios>,) => {
      
      
      return axios<void>(
      {url: `/document/delete/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteDocumentDeleteIdMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentDeleteId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentDeleteId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteDocumentDeleteId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDocumentDeleteId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteDocumentDeleteId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteDocumentDeleteIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDocumentDeleteId>>>
    
    export type DeleteDocumentDeleteIdMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Delete a document
 */
export const useDeleteDocumentDeleteId = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentDeleteId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDocumentDeleteId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteDocumentDeleteIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get all documents
 */
export const getDocumentGetAllDocuments = (
    
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {
      
      
      return axios<DocumentsArray>(
      {url: `/document/getAllDocuments`, method: 'GET', signal
    },
      options);
    }
  



export const getGetDocumentGetAllDocumentsQueryKey = () => {
    return [
    `/document/getAllDocuments`
    ] as const;
    }

    
export const getGetDocumentGetAllDocumentsQueryOptions = <TData = Awaited<ReturnType<typeof getDocumentGetAllDocuments>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentGetAllDocuments>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentGetAllDocumentsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocumentGetAllDocuments>>> = ({ signal }) => getDocumentGetAllDocuments(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocumentGetAllDocuments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentGetAllDocumentsQueryResult = NonNullable<Awaited<ReturnType<typeof getDocumentGetAllDocuments>>>
export type GetDocumentGetAllDocumentsQueryError = ErrorType<unknown>


export function useGetDocumentGetAllDocuments<TData = Awaited<ReturnType<typeof getDocumentGetAllDocuments>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentGetAllDocuments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentGetAllDocuments>>,
          TError,
          Awaited<ReturnType<typeof getDocumentGetAllDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentGetAllDocuments<TData = Awaited<ReturnType<typeof getDocumentGetAllDocuments>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentGetAllDocuments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentGetAllDocuments>>,
          TError,
          Awaited<ReturnType<typeof getDocumentGetAllDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentGetAllDocuments<TData = Awaited<ReturnType<typeof getDocumentGetAllDocuments>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentGetAllDocuments>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all documents
 */

export function useGetDocumentGetAllDocuments<TData = Awaited<ReturnType<typeof getDocumentGetAllDocuments>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentGetAllDocuments>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDocumentGetAllDocumentsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get a document by id
 */
export const getDocumentGetDocumentByIdId = (
    id: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {
      
      
      return axios<Document>(
      {url: `/document/getDocumentById/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetDocumentGetDocumentByIdIdQueryKey = (id?: string,) => {
    return [
    `/document/getDocumentById/${id}`
    ] as const;
    }

    
export const getGetDocumentGetDocumentByIdIdQueryOptions = <TData = Awaited<ReturnType<typeof getDocumentGetDocumentByIdId>>, TError = ErrorType<ErrorResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentGetDocumentByIdId>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentGetDocumentByIdIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocumentGetDocumentByIdId>>> = ({ signal }) => getDocumentGetDocumentByIdId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocumentGetDocumentByIdId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentGetDocumentByIdIdQueryResult = NonNullable<Awaited<ReturnType<typeof getDocumentGetDocumentByIdId>>>
export type GetDocumentGetDocumentByIdIdQueryError = ErrorType<ErrorResponse>


export function useGetDocumentGetDocumentByIdId<TData = Awaited<ReturnType<typeof getDocumentGetDocumentByIdId>>, TError = ErrorType<ErrorResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentGetDocumentByIdId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentGetDocumentByIdId>>,
          TError,
          Awaited<ReturnType<typeof getDocumentGetDocumentByIdId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentGetDocumentByIdId<TData = Awaited<ReturnType<typeof getDocumentGetDocumentByIdId>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentGetDocumentByIdId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentGetDocumentByIdId>>,
          TError,
          Awaited<ReturnType<typeof getDocumentGetDocumentByIdId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentGetDocumentByIdId<TData = Awaited<ReturnType<typeof getDocumentGetDocumentByIdId>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentGetDocumentByIdId>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a document by id
 */

export function useGetDocumentGetDocumentByIdId<TData = Awaited<ReturnType<typeof getDocumentGetDocumentByIdId>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentGetDocumentByIdId>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDocumentGetDocumentByIdIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get documents by name
 */
export const getDocumentGetDocumentsByNameName = (
    name: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {
      
      
      return axios<DocumentsArray>(
      {url: `/document/getDocumentsByName/${name}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetDocumentGetDocumentsByNameNameQueryKey = (name?: string,) => {
    return [
    `/document/getDocumentsByName/${name}`
    ] as const;
    }

    
export const getGetDocumentGetDocumentsByNameNameQueryOptions = <TData = Awaited<ReturnType<typeof getDocumentGetDocumentsByNameName>>, TError = ErrorType<unknown>>(name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentGetDocumentsByNameName>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentGetDocumentsByNameNameQueryKey(name);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocumentGetDocumentsByNameName>>> = ({ signal }) => getDocumentGetDocumentsByNameName(name, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(name), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocumentGetDocumentsByNameName>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentGetDocumentsByNameNameQueryResult = NonNullable<Awaited<ReturnType<typeof getDocumentGetDocumentsByNameName>>>
export type GetDocumentGetDocumentsByNameNameQueryError = ErrorType<unknown>


export function useGetDocumentGetDocumentsByNameName<TData = Awaited<ReturnType<typeof getDocumentGetDocumentsByNameName>>, TError = ErrorType<unknown>>(
 name: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentGetDocumentsByNameName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentGetDocumentsByNameName>>,
          TError,
          Awaited<ReturnType<typeof getDocumentGetDocumentsByNameName>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentGetDocumentsByNameName<TData = Awaited<ReturnType<typeof getDocumentGetDocumentsByNameName>>, TError = ErrorType<unknown>>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentGetDocumentsByNameName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentGetDocumentsByNameName>>,
          TError,
          Awaited<ReturnType<typeof getDocumentGetDocumentsByNameName>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentGetDocumentsByNameName<TData = Awaited<ReturnType<typeof getDocumentGetDocumentsByNameName>>, TError = ErrorType<unknown>>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentGetDocumentsByNameName>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get documents by name
 */

export function useGetDocumentGetDocumentsByNameName<TData = Awaited<ReturnType<typeof getDocumentGetDocumentsByNameName>>, TError = ErrorType<unknown>>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentGetDocumentsByNameName>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDocumentGetDocumentsByNameNameQueryOptions(name,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



