/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * RAG Document Chat API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  MessageResponse
} from '.././model';

import { axios } from '.././axios';
import type { ErrorType } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Index document chunks
 */
export const postDocumentChunksIndexDocumentChunksDocumentId = (
    documentId: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {
      
      
      return axios<MessageResponse>(
      {url: `/document-chunks/indexDocumentChunks/${documentId}`, method: 'POST', signal
    },
      options);
    }
  


export const getPostDocumentChunksIndexDocumentChunksDocumentIdMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postDocumentChunksIndexDocumentChunksDocumentId>>, TError,{documentId: string}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof postDocumentChunksIndexDocumentChunksDocumentId>>, TError,{documentId: string}, TContext> => {

const mutationKey = ['postDocumentChunksIndexDocumentChunksDocumentId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postDocumentChunksIndexDocumentChunksDocumentId>>, {documentId: string}> = (props) => {
          const {documentId} = props ?? {};

          return  postDocumentChunksIndexDocumentChunksDocumentId(documentId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostDocumentChunksIndexDocumentChunksDocumentIdMutationResult = NonNullable<Awaited<ReturnType<typeof postDocumentChunksIndexDocumentChunksDocumentId>>>
    
    export type PostDocumentChunksIndexDocumentChunksDocumentIdMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Index document chunks
 */
export const usePostDocumentChunksIndexDocumentChunksDocumentId = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postDocumentChunksIndexDocumentChunksDocumentId>>, TError,{documentId: string}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postDocumentChunksIndexDocumentChunksDocumentId>>,
        TError,
        {documentId: string},
        TContext
      > => {

      const mutationOptions = getPostDocumentChunksIndexDocumentChunksDocumentIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    