/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * RAG Document Chat API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateDocumentChatRequest,
  DocumentChatsArray,
  ErrorResponse,
  GetDocumentChatsGetByChatIdParams,
  GetDocumentChatsGetByDocumentIdParams
} from '.././model';

import { axios } from '.././axios';
import type { ErrorType , BodyType } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Create a document-chat relation
 */
export const postDocumentChatsCreate = (
    createDocumentChatRequest: BodyType<CreateDocumentChatRequest>,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {
      
      
      return axios<DocumentChatsArray>(
      {url: `/document-chats/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createDocumentChatRequest, signal
    },
      options);
    }
  


export const getPostDocumentChatsCreateMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postDocumentChatsCreate>>, TError,{data: BodyType<CreateDocumentChatRequest>}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof postDocumentChatsCreate>>, TError,{data: BodyType<CreateDocumentChatRequest>}, TContext> => {

const mutationKey = ['postDocumentChatsCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postDocumentChatsCreate>>, {data: BodyType<CreateDocumentChatRequest>}> = (props) => {
          const {data} = props ?? {};

          return  postDocumentChatsCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostDocumentChatsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof postDocumentChatsCreate>>>
    export type PostDocumentChatsCreateMutationBody = BodyType<CreateDocumentChatRequest>
    export type PostDocumentChatsCreateMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Create a document-chat relation
 */
export const usePostDocumentChatsCreate = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postDocumentChatsCreate>>, TError,{data: BodyType<CreateDocumentChatRequest>}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postDocumentChatsCreate>>,
        TError,
        {data: BodyType<CreateDocumentChatRequest>},
        TContext
      > => {

      const mutationOptions = getPostDocumentChatsCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete document-chat relations by chat id
 */
export const deleteDocumentChatsDeleteByChatIdId = (
    id: string,
 options?: SecondParameter<typeof axios>,) => {
      
      
      return axios<void>(
      {url: `/document-chats/deleteByChatId/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteDocumentChatsDeleteByChatIdIdMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentChatsDeleteByChatIdId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentChatsDeleteByChatIdId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteDocumentChatsDeleteByChatIdId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDocumentChatsDeleteByChatIdId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteDocumentChatsDeleteByChatIdId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteDocumentChatsDeleteByChatIdIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDocumentChatsDeleteByChatIdId>>>
    
    export type DeleteDocumentChatsDeleteByChatIdIdMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Delete document-chat relations by chat id
 */
export const useDeleteDocumentChatsDeleteByChatIdId = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentChatsDeleteByChatIdId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDocumentChatsDeleteByChatIdId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteDocumentChatsDeleteByChatIdIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete document-chat relations by document id
 */
export const deleteDocumentChatsDeleteByDocumentIdId = (
    id: string,
 options?: SecondParameter<typeof axios>,) => {
      
      
      return axios<void>(
      {url: `/document-chats/deleteByDocumentId/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteDocumentChatsDeleteByDocumentIdIdMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentChatsDeleteByDocumentIdId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentChatsDeleteByDocumentIdId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteDocumentChatsDeleteByDocumentIdId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDocumentChatsDeleteByDocumentIdId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteDocumentChatsDeleteByDocumentIdId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteDocumentChatsDeleteByDocumentIdIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDocumentChatsDeleteByDocumentIdId>>>
    
    export type DeleteDocumentChatsDeleteByDocumentIdIdMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Delete document-chat relations by document id
 */
export const useDeleteDocumentChatsDeleteByDocumentIdId = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDocumentChatsDeleteByDocumentIdId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDocumentChatsDeleteByDocumentIdId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteDocumentChatsDeleteByDocumentIdIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get document-chat relations by document id
 */
export const getDocumentChatsGetByDocumentId = (
    params: GetDocumentChatsGetByDocumentIdParams,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {
      
      
      return axios<DocumentChatsArray>(
      {url: `/document-chats/getByDocumentId`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetDocumentChatsGetByDocumentIdQueryKey = (params?: GetDocumentChatsGetByDocumentIdParams,) => {
    return [
    `/document-chats/getByDocumentId`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetDocumentChatsGetByDocumentIdQueryOptions = <TData = Awaited<ReturnType<typeof getDocumentChatsGetByDocumentId>>, TError = ErrorType<unknown>>(params: GetDocumentChatsGetByDocumentIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentChatsGetByDocumentId>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentChatsGetByDocumentIdQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocumentChatsGetByDocumentId>>> = ({ signal }) => getDocumentChatsGetByDocumentId(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocumentChatsGetByDocumentId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentChatsGetByDocumentIdQueryResult = NonNullable<Awaited<ReturnType<typeof getDocumentChatsGetByDocumentId>>>
export type GetDocumentChatsGetByDocumentIdQueryError = ErrorType<unknown>


export function useGetDocumentChatsGetByDocumentId<TData = Awaited<ReturnType<typeof getDocumentChatsGetByDocumentId>>, TError = ErrorType<unknown>>(
 params: GetDocumentChatsGetByDocumentIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentChatsGetByDocumentId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentChatsGetByDocumentId>>,
          TError,
          Awaited<ReturnType<typeof getDocumentChatsGetByDocumentId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentChatsGetByDocumentId<TData = Awaited<ReturnType<typeof getDocumentChatsGetByDocumentId>>, TError = ErrorType<unknown>>(
 params: GetDocumentChatsGetByDocumentIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentChatsGetByDocumentId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentChatsGetByDocumentId>>,
          TError,
          Awaited<ReturnType<typeof getDocumentChatsGetByDocumentId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentChatsGetByDocumentId<TData = Awaited<ReturnType<typeof getDocumentChatsGetByDocumentId>>, TError = ErrorType<unknown>>(
 params: GetDocumentChatsGetByDocumentIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentChatsGetByDocumentId>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get document-chat relations by document id
 */

export function useGetDocumentChatsGetByDocumentId<TData = Awaited<ReturnType<typeof getDocumentChatsGetByDocumentId>>, TError = ErrorType<unknown>>(
 params: GetDocumentChatsGetByDocumentIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentChatsGetByDocumentId>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDocumentChatsGetByDocumentIdQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get document-chat relations by chat id
 */
export const getDocumentChatsGetByChatId = (
    params: GetDocumentChatsGetByChatIdParams,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {
      
      
      return axios<DocumentChatsArray>(
      {url: `/document-chats/getByChatId`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetDocumentChatsGetByChatIdQueryKey = (params?: GetDocumentChatsGetByChatIdParams,) => {
    return [
    `/document-chats/getByChatId`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetDocumentChatsGetByChatIdQueryOptions = <TData = Awaited<ReturnType<typeof getDocumentChatsGetByChatId>>, TError = ErrorType<unknown>>(params: GetDocumentChatsGetByChatIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentChatsGetByChatId>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentChatsGetByChatIdQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocumentChatsGetByChatId>>> = ({ signal }) => getDocumentChatsGetByChatId(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocumentChatsGetByChatId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentChatsGetByChatIdQueryResult = NonNullable<Awaited<ReturnType<typeof getDocumentChatsGetByChatId>>>
export type GetDocumentChatsGetByChatIdQueryError = ErrorType<unknown>


export function useGetDocumentChatsGetByChatId<TData = Awaited<ReturnType<typeof getDocumentChatsGetByChatId>>, TError = ErrorType<unknown>>(
 params: GetDocumentChatsGetByChatIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentChatsGetByChatId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentChatsGetByChatId>>,
          TError,
          Awaited<ReturnType<typeof getDocumentChatsGetByChatId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentChatsGetByChatId<TData = Awaited<ReturnType<typeof getDocumentChatsGetByChatId>>, TError = ErrorType<unknown>>(
 params: GetDocumentChatsGetByChatIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentChatsGetByChatId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentChatsGetByChatId>>,
          TError,
          Awaited<ReturnType<typeof getDocumentChatsGetByChatId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentChatsGetByChatId<TData = Awaited<ReturnType<typeof getDocumentChatsGetByChatId>>, TError = ErrorType<unknown>>(
 params: GetDocumentChatsGetByChatIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentChatsGetByChatId>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get document-chat relations by chat id
 */

export function useGetDocumentChatsGetByChatId<TData = Awaited<ReturnType<typeof getDocumentChatsGetByChatId>>, TError = ErrorType<unknown>>(
 params: GetDocumentChatsGetByChatIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentChatsGetByChatId>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDocumentChatsGetByChatIdQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



