/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * RAG Document Chat API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Chat,
  ChatsArray,
  CreateChatRequest,
  CreateMessageRequest,
  ErrorResponse,
  PostChatSendMessage200
} from '.././model';

import { axios } from '.././axios';
import type { ErrorType , BodyType } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Send a message
 */
export const postChatSendMessage = (
    createMessageRequest: BodyType<CreateMessageRequest>,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {
      
      
      return axios<PostChatSendMessage200>(
      {url: `/chat/sendMessage`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createMessageRequest, signal
    },
      options);
    }
  


export const getPostChatSendMessageMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChatSendMessage>>, TError,{data: BodyType<CreateMessageRequest>}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof postChatSendMessage>>, TError,{data: BodyType<CreateMessageRequest>}, TContext> => {

const mutationKey = ['postChatSendMessage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postChatSendMessage>>, {data: BodyType<CreateMessageRequest>}> = (props) => {
          const {data} = props ?? {};

          return  postChatSendMessage(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostChatSendMessageMutationResult = NonNullable<Awaited<ReturnType<typeof postChatSendMessage>>>
    export type PostChatSendMessageMutationBody = BodyType<CreateMessageRequest>
    export type PostChatSendMessageMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Send a message
 */
export const usePostChatSendMessage = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChatSendMessage>>, TError,{data: BodyType<CreateMessageRequest>}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postChatSendMessage>>,
        TError,
        {data: BodyType<CreateMessageRequest>},
        TContext
      > => {

      const mutationOptions = getPostChatSendMessageMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Create a new chat
 */
export const postChatCreate = (
    createChatRequest: BodyType<CreateChatRequest>,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {
      
      
      return axios<Chat>(
      {url: `/chat/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createChatRequest, signal
    },
      options);
    }
  


export const getPostChatCreateMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChatCreate>>, TError,{data: BodyType<CreateChatRequest>}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof postChatCreate>>, TError,{data: BodyType<CreateChatRequest>}, TContext> => {

const mutationKey = ['postChatCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postChatCreate>>, {data: BodyType<CreateChatRequest>}> = (props) => {
          const {data} = props ?? {};

          return  postChatCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostChatCreateMutationResult = NonNullable<Awaited<ReturnType<typeof postChatCreate>>>
    export type PostChatCreateMutationBody = BodyType<CreateChatRequest>
    export type PostChatCreateMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Create a new chat
 */
export const usePostChatCreate = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChatCreate>>, TError,{data: BodyType<CreateChatRequest>}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postChatCreate>>,
        TError,
        {data: BodyType<CreateChatRequest>},
        TContext
      > => {

      const mutationOptions = getPostChatCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get all chats
 */
export const getChatGetAllChats = (
    
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {
      
      
      return axios<ChatsArray>(
      {url: `/chat/getAllChats`, method: 'GET', signal
    },
      options);
    }
  



export const getGetChatGetAllChatsQueryKey = () => {
    return [
    `/chat/getAllChats`
    ] as const;
    }

    
export const getGetChatGetAllChatsQueryOptions = <TData = Awaited<ReturnType<typeof getChatGetAllChats>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatGetAllChats>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChatGetAllChatsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChatGetAllChats>>> = ({ signal }) => getChatGetAllChats(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChatGetAllChats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetChatGetAllChatsQueryResult = NonNullable<Awaited<ReturnType<typeof getChatGetAllChats>>>
export type GetChatGetAllChatsQueryError = ErrorType<unknown>


export function useGetChatGetAllChats<TData = Awaited<ReturnType<typeof getChatGetAllChats>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatGetAllChats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatGetAllChats>>,
          TError,
          Awaited<ReturnType<typeof getChatGetAllChats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChatGetAllChats<TData = Awaited<ReturnType<typeof getChatGetAllChats>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatGetAllChats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatGetAllChats>>,
          TError,
          Awaited<ReturnType<typeof getChatGetAllChats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChatGetAllChats<TData = Awaited<ReturnType<typeof getChatGetAllChats>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatGetAllChats>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all chats
 */

export function useGetChatGetAllChats<TData = Awaited<ReturnType<typeof getChatGetAllChats>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatGetAllChats>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetChatGetAllChatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get chat by id
 */
export const getChatGetChatByIdId = (
    id: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {
      
      
      return axios<Chat>(
      {url: `/chat/getChatById/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetChatGetChatByIdIdQueryKey = (id?: string,) => {
    return [
    `/chat/getChatById/${id}`
    ] as const;
    }

    
export const getGetChatGetChatByIdIdQueryOptions = <TData = Awaited<ReturnType<typeof getChatGetChatByIdId>>, TError = ErrorType<ErrorResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatGetChatByIdId>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChatGetChatByIdIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChatGetChatByIdId>>> = ({ signal }) => getChatGetChatByIdId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChatGetChatByIdId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetChatGetChatByIdIdQueryResult = NonNullable<Awaited<ReturnType<typeof getChatGetChatByIdId>>>
export type GetChatGetChatByIdIdQueryError = ErrorType<ErrorResponse>


export function useGetChatGetChatByIdId<TData = Awaited<ReturnType<typeof getChatGetChatByIdId>>, TError = ErrorType<ErrorResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatGetChatByIdId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatGetChatByIdId>>,
          TError,
          Awaited<ReturnType<typeof getChatGetChatByIdId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChatGetChatByIdId<TData = Awaited<ReturnType<typeof getChatGetChatByIdId>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatGetChatByIdId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatGetChatByIdId>>,
          TError,
          Awaited<ReturnType<typeof getChatGetChatByIdId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChatGetChatByIdId<TData = Awaited<ReturnType<typeof getChatGetChatByIdId>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatGetChatByIdId>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get chat by id
 */

export function useGetChatGetChatByIdId<TData = Awaited<ReturnType<typeof getChatGetChatByIdId>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatGetChatByIdId>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetChatGetChatByIdIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Delete a chat
 */
export const deleteChatDeleteId = (
    id: string,
 options?: SecondParameter<typeof axios>,) => {
      
      
      return axios<void>(
      {url: `/chat/delete/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteChatDeleteIdMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChatDeleteId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteChatDeleteId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteChatDeleteId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteChatDeleteId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteChatDeleteId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteChatDeleteIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteChatDeleteId>>>
    
    export type DeleteChatDeleteIdMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Delete a chat
 */
export const useDeleteChatDeleteId = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChatDeleteId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteChatDeleteId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteChatDeleteIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    