/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * RAG Document Chat API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateMessageRequest,
  ErrorResponse,
  Message,
  MessagesArray
} from '.././model';

import { axios } from '.././axios';
import type { ErrorType , BodyType } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Create a message
 */
export const postMessageCreate = (
    createMessageRequest: BodyType<CreateMessageRequest>,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {
      
      
      return axios<Message>(
      {url: `/message/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createMessageRequest, signal
    },
      options);
    }
  


export const getPostMessageCreateMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMessageCreate>>, TError,{data: BodyType<CreateMessageRequest>}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof postMessageCreate>>, TError,{data: BodyType<CreateMessageRequest>}, TContext> => {

const mutationKey = ['postMessageCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postMessageCreate>>, {data: BodyType<CreateMessageRequest>}> = (props) => {
          const {data} = props ?? {};

          return  postMessageCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostMessageCreateMutationResult = NonNullable<Awaited<ReturnType<typeof postMessageCreate>>>
    export type PostMessageCreateMutationBody = BodyType<CreateMessageRequest>
    export type PostMessageCreateMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Create a message
 */
export const usePostMessageCreate = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMessageCreate>>, TError,{data: BodyType<CreateMessageRequest>}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postMessageCreate>>,
        TError,
        {data: BodyType<CreateMessageRequest>},
        TContext
      > => {

      const mutationOptions = getPostMessageCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get all messages
 */
export const getMessageGetAllMessages = (
    
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {
      
      
      return axios<MessagesArray>(
      {url: `/message/getAllMessages`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMessageGetAllMessagesQueryKey = () => {
    return [
    `/message/getAllMessages`
    ] as const;
    }

    
export const getGetMessageGetAllMessagesQueryOptions = <TData = Awaited<ReturnType<typeof getMessageGetAllMessages>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetAllMessages>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMessageGetAllMessagesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMessageGetAllMessages>>> = ({ signal }) => getMessageGetAllMessages(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMessageGetAllMessages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMessageGetAllMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof getMessageGetAllMessages>>>
export type GetMessageGetAllMessagesQueryError = ErrorType<unknown>


export function useGetMessageGetAllMessages<TData = Awaited<ReturnType<typeof getMessageGetAllMessages>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetAllMessages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessageGetAllMessages>>,
          TError,
          Awaited<ReturnType<typeof getMessageGetAllMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessageGetAllMessages<TData = Awaited<ReturnType<typeof getMessageGetAllMessages>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetAllMessages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessageGetAllMessages>>,
          TError,
          Awaited<ReturnType<typeof getMessageGetAllMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessageGetAllMessages<TData = Awaited<ReturnType<typeof getMessageGetAllMessages>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetAllMessages>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all messages
 */

export function useGetMessageGetAllMessages<TData = Awaited<ReturnType<typeof getMessageGetAllMessages>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetAllMessages>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMessageGetAllMessagesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get message by id
 */
export const getMessageGetMessageByIdId = (
    id: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {
      
      
      return axios<Message>(
      {url: `/message/getMessageById/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMessageGetMessageByIdIdQueryKey = (id?: string,) => {
    return [
    `/message/getMessageById/${id}`
    ] as const;
    }

    
export const getGetMessageGetMessageByIdIdQueryOptions = <TData = Awaited<ReturnType<typeof getMessageGetMessageByIdId>>, TError = ErrorType<ErrorResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessageByIdId>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMessageGetMessageByIdIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMessageGetMessageByIdId>>> = ({ signal }) => getMessageGetMessageByIdId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessageByIdId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMessageGetMessageByIdIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMessageGetMessageByIdId>>>
export type GetMessageGetMessageByIdIdQueryError = ErrorType<ErrorResponse>


export function useGetMessageGetMessageByIdId<TData = Awaited<ReturnType<typeof getMessageGetMessageByIdId>>, TError = ErrorType<ErrorResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessageByIdId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessageGetMessageByIdId>>,
          TError,
          Awaited<ReturnType<typeof getMessageGetMessageByIdId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessageGetMessageByIdId<TData = Awaited<ReturnType<typeof getMessageGetMessageByIdId>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessageByIdId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessageGetMessageByIdId>>,
          TError,
          Awaited<ReturnType<typeof getMessageGetMessageByIdId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessageGetMessageByIdId<TData = Awaited<ReturnType<typeof getMessageGetMessageByIdId>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessageByIdId>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get message by id
 */

export function useGetMessageGetMessageByIdId<TData = Awaited<ReturnType<typeof getMessageGetMessageByIdId>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessageByIdId>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMessageGetMessageByIdIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get messages by role
 */
export const getMessageGetMessageByRoleRole = (
    role: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {
      
      
      return axios<MessagesArray>(
      {url: `/message/getMessageByRole/${role}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMessageGetMessageByRoleRoleQueryKey = (role?: string,) => {
    return [
    `/message/getMessageByRole/${role}`
    ] as const;
    }

    
export const getGetMessageGetMessageByRoleRoleQueryOptions = <TData = Awaited<ReturnType<typeof getMessageGetMessageByRoleRole>>, TError = ErrorType<unknown>>(role: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessageByRoleRole>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMessageGetMessageByRoleRoleQueryKey(role);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMessageGetMessageByRoleRole>>> = ({ signal }) => getMessageGetMessageByRoleRole(role, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(role), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessageByRoleRole>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMessageGetMessageByRoleRoleQueryResult = NonNullable<Awaited<ReturnType<typeof getMessageGetMessageByRoleRole>>>
export type GetMessageGetMessageByRoleRoleQueryError = ErrorType<unknown>


export function useGetMessageGetMessageByRoleRole<TData = Awaited<ReturnType<typeof getMessageGetMessageByRoleRole>>, TError = ErrorType<unknown>>(
 role: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessageByRoleRole>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessageGetMessageByRoleRole>>,
          TError,
          Awaited<ReturnType<typeof getMessageGetMessageByRoleRole>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessageGetMessageByRoleRole<TData = Awaited<ReturnType<typeof getMessageGetMessageByRoleRole>>, TError = ErrorType<unknown>>(
 role: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessageByRoleRole>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessageGetMessageByRoleRole>>,
          TError,
          Awaited<ReturnType<typeof getMessageGetMessageByRoleRole>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessageGetMessageByRoleRole<TData = Awaited<ReturnType<typeof getMessageGetMessageByRoleRole>>, TError = ErrorType<unknown>>(
 role: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessageByRoleRole>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get messages by role
 */

export function useGetMessageGetMessageByRoleRole<TData = Awaited<ReturnType<typeof getMessageGetMessageByRoleRole>>, TError = ErrorType<unknown>>(
 role: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessageByRoleRole>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMessageGetMessageByRoleRoleQueryOptions(role,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get messages by chat id
 */
export const getMessageGetMessagesByChatIdChatId = (
    chatId: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {
      
      
      return axios<MessagesArray>(
      {url: `/message/getMessagesByChatId/${chatId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMessageGetMessagesByChatIdChatIdQueryKey = (chatId?: string,) => {
    return [
    `/message/getMessagesByChatId/${chatId}`
    ] as const;
    }

    
export const getGetMessageGetMessagesByChatIdChatIdQueryOptions = <TData = Awaited<ReturnType<typeof getMessageGetMessagesByChatIdChatId>>, TError = ErrorType<unknown>>(chatId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessagesByChatIdChatId>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMessageGetMessagesByChatIdChatIdQueryKey(chatId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMessageGetMessagesByChatIdChatId>>> = ({ signal }) => getMessageGetMessagesByChatIdChatId(chatId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(chatId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessagesByChatIdChatId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMessageGetMessagesByChatIdChatIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMessageGetMessagesByChatIdChatId>>>
export type GetMessageGetMessagesByChatIdChatIdQueryError = ErrorType<unknown>


export function useGetMessageGetMessagesByChatIdChatId<TData = Awaited<ReturnType<typeof getMessageGetMessagesByChatIdChatId>>, TError = ErrorType<unknown>>(
 chatId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessagesByChatIdChatId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessageGetMessagesByChatIdChatId>>,
          TError,
          Awaited<ReturnType<typeof getMessageGetMessagesByChatIdChatId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessageGetMessagesByChatIdChatId<TData = Awaited<ReturnType<typeof getMessageGetMessagesByChatIdChatId>>, TError = ErrorType<unknown>>(
 chatId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessagesByChatIdChatId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessageGetMessagesByChatIdChatId>>,
          TError,
          Awaited<ReturnType<typeof getMessageGetMessagesByChatIdChatId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessageGetMessagesByChatIdChatId<TData = Awaited<ReturnType<typeof getMessageGetMessagesByChatIdChatId>>, TError = ErrorType<unknown>>(
 chatId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessagesByChatIdChatId>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get messages by chat id
 */

export function useGetMessageGetMessagesByChatIdChatId<TData = Awaited<ReturnType<typeof getMessageGetMessagesByChatIdChatId>>, TError = ErrorType<unknown>>(
 chatId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessagesByChatIdChatId>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMessageGetMessagesByChatIdChatIdQueryOptions(chatId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get messages by chat id and role
 */
export const getMessageGetMessagesByChatIdAndRoleChatIdRole = (
    chatId: string,
    role: string,
 options?: SecondParameter<typeof axios>,signal?: AbortSignal
) => {
      
      
      return axios<MessagesArray>(
      {url: `/message/getMessagesByChatIdAndRole/${chatId}/${role}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMessageGetMessagesByChatIdAndRoleChatIdRoleQueryKey = (chatId?: string,
    role?: string,) => {
    return [
    `/message/getMessagesByChatIdAndRole/${chatId}/${role}`
    ] as const;
    }

    
export const getGetMessageGetMessagesByChatIdAndRoleChatIdRoleQueryOptions = <TData = Awaited<ReturnType<typeof getMessageGetMessagesByChatIdAndRoleChatIdRole>>, TError = ErrorType<unknown>>(chatId: string,
    role: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessagesByChatIdAndRoleChatIdRole>>, TError, TData>>, request?: SecondParameter<typeof axios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMessageGetMessagesByChatIdAndRoleChatIdRoleQueryKey(chatId,role);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMessageGetMessagesByChatIdAndRoleChatIdRole>>> = ({ signal }) => getMessageGetMessagesByChatIdAndRoleChatIdRole(chatId,role, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(chatId && role), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessagesByChatIdAndRoleChatIdRole>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMessageGetMessagesByChatIdAndRoleChatIdRoleQueryResult = NonNullable<Awaited<ReturnType<typeof getMessageGetMessagesByChatIdAndRoleChatIdRole>>>
export type GetMessageGetMessagesByChatIdAndRoleChatIdRoleQueryError = ErrorType<unknown>


export function useGetMessageGetMessagesByChatIdAndRoleChatIdRole<TData = Awaited<ReturnType<typeof getMessageGetMessagesByChatIdAndRoleChatIdRole>>, TError = ErrorType<unknown>>(
 chatId: string,
    role: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessagesByChatIdAndRoleChatIdRole>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessageGetMessagesByChatIdAndRoleChatIdRole>>,
          TError,
          Awaited<ReturnType<typeof getMessageGetMessagesByChatIdAndRoleChatIdRole>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessageGetMessagesByChatIdAndRoleChatIdRole<TData = Awaited<ReturnType<typeof getMessageGetMessagesByChatIdAndRoleChatIdRole>>, TError = ErrorType<unknown>>(
 chatId: string,
    role: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessagesByChatIdAndRoleChatIdRole>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessageGetMessagesByChatIdAndRoleChatIdRole>>,
          TError,
          Awaited<ReturnType<typeof getMessageGetMessagesByChatIdAndRoleChatIdRole>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessageGetMessagesByChatIdAndRoleChatIdRole<TData = Awaited<ReturnType<typeof getMessageGetMessagesByChatIdAndRoleChatIdRole>>, TError = ErrorType<unknown>>(
 chatId: string,
    role: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessagesByChatIdAndRoleChatIdRole>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get messages by chat id and role
 */

export function useGetMessageGetMessagesByChatIdAndRoleChatIdRole<TData = Awaited<ReturnType<typeof getMessageGetMessagesByChatIdAndRoleChatIdRole>>, TError = ErrorType<unknown>>(
 chatId: string,
    role: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGetMessagesByChatIdAndRoleChatIdRole>>, TError, TData>>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMessageGetMessagesByChatIdAndRoleChatIdRoleQueryOptions(chatId,role,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Delete a message
 */
export const deleteMessageDeleteId = (
    id: string,
 options?: SecondParameter<typeof axios>,) => {
      
      
      return axios<void>(
      {url: `/message/delete/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteMessageDeleteIdMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMessageDeleteId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteMessageDeleteId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteMessageDeleteId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMessageDeleteId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteMessageDeleteId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteMessageDeleteIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMessageDeleteId>>>
    
    export type DeleteMessageDeleteIdMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Delete a message
 */
export const useDeleteMessageDeleteId = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMessageDeleteId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMessageDeleteId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteMessageDeleteIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    